apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheusUID
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      exemplars: true

  - name: Tempo
    type: tempo
    access: proxy
    uid: tempoUID
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheusUID
      search:
        hide: false
      nodeGraph:
        enabled: true
